[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
runOnSave = false
port = 8502

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
fastReruns = true
magicEnabled = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s" 